env:
  # fix windows timeout
  # https://travis-ci.community/t/timeout-after-build-finished-and-succeeded/1336
  - YARN_GPG=no
os:
  - linux
  - osx
  - windows
dist: bionic
services:
  - xvfb
language: node_js
node_js:
  - "lts/*"
filter_secrets: false
cache:
  yarn: true
before_install:
  - npm install --global nyc yarn
install:
  - yarn
script:
  - yarn lint
  - yarn build
  - yarn test-coverage
after_script:
  - npm install --global codecov coveralls
  - nyc report --reporter=text-lcov | coveralls
  - nyc report --reporter=text-lcov | codecov
