# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

strategy:
  matrix:
    node_8_x:
      imageName: "ubuntu-16.04"
      node_version: 8.x
    node_10_x:
      imageName: "ubuntu-16.04"
      node_version: 10.x
    node_12_x:
      imageName: "ubuntu-16.04"
      node_version: 12.x
    mac:
      imageName: "macOS-10.14"
      node_version: 12.x
    windows:
      imageName: "windows-2019"
      node_version: 12.x

trigger:
  - master

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
      checkLatest: true
    displayName: "Install Node.js"

  - script: |
      yarn
    displayName: "Yarn install"

  - script: |
      yarn lint
    displayName: "Yarn lint"

  - script: |
      yarn build
    displayName: "Yarn build"

  - script: |
      npm install --global nyc
    displayName: "Install nyc"

  - script: |
      sudo cp scripts/xvfb.init /etc/init.d/xvfb
      sudo chmod +x /etc/init.d/xvfb
      sudo update-rc.d xvfb defaults
      sudo service xvfb start
    condition: eq( variables['Agent.OS'], 'Linux' )
    displayName: "Linux Setup"

  - script: |
      yarn test-coverage
    displayName: "test-coverage"
    env:
      DISPLAY: :10 # Only necessary for linux tests
      YARN_GPG: no # windows

  - script: |
      npm install --global codecov coveralls
      nyc report --reporter=text-lcov | coveralls
      nyc report --reporter=text-lcov | codecov
    displayName: "report-coverage"
